### ISSUE TITLE
run (shell specific?): allow for background mode?

### ISSUE THREAD

**Issue by yarikoptic** [vsoch/qme#30]
ATM `qme run` execution awaits for completion of the task. Being able to just submit for running the task in the background would be super useful.

**Comment by vsoch** [comment]
Yes but how would you implement that?

**Comment by yarikoptic** [comment]
;-) good question... quick and ugly could be as

```shell
$> python -c 'import os; os.system( "bash -c \"{ sleep 4; echo done; } & disown\" " )'; echo exited; sleep 2; echo slept
exited
slept
$> done
```
ie qwe could just start a new one of itself (but in foreground) and detach.  But I think there is a more "natural" way... we did something like that in fail2ban but I had not touched that project for so long and it changed so much that I can't quickly find... theoretically IIRC it is -- "fork into a new child subprocess;  child continues; parent quits"... ha -- I said "fork" and that lead me to a new search within fail2ban to immediately find it:
https://github.com/fail2ban/fail2ban/blob/master/fail2ban/server/server.py#L842

**Comment by vsoch** [comment]
How would we capture the result and return code then? This could be appropriate for an executor that doesn't need those variables (and I don't think I'd use os.system, I've read somewhere that's not great practice) but not for a basic shell executor that requires them.

**Comment by vsoch** [comment]
I think I'm leaning on the side of being conservative with respect to using os.fork, os.system, or subprocess with shell=True, but I do think there are libraries we can try get at async, or just test using a & as a user normally would. See https://stackoverflow.com/questions/30157895/does-python-os-fork-uses-the-same-python-interpreter for some of my concerns, and let's pick up discussion around this in #2, which I've been thinking about since I started the library! Closing this issue, let's pick up in #2.
